server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true   # TODO: zakomentarosati

      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post-service/**
          filters:
            - name: SpecialClass
              order: -2
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - name: SpecialClass
#              order: -2
#            - name: CircuitBreaker
#              args:
#                name: korisnik-servis-circuit-breaker
#                fallbackUri: forward:/korisnik-servis-circuit-breaker
        - id: connection-service
          uri: lb://connection-service
          predicates:
              - Path=/connection-service/**
          filters:
            - name: SpecialClass
              order: -2
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker
#              order: 2
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - name: SpecialClass
              order: -2
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY