server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:


      
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: korisnik-servis
          uri: http://korisnik-servis
          predicates:
            - Path=/korisnik-servis/**
          filters:
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker
        - id: post-service
          uri: http://post-service
          predicates:
            - Path=/post-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker
        - id: connection-service
          uri: http://connection-service
          predicates:
              - Path=/connection-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker
        - id: auth-service
          uri: http://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: korisnik-servis-circuit-breaker
                fallbackUri: forward:/korisnik-servis-circuit-breaker
        - id: studijski-program-servis
          uri: http://studijski-program-servis
          predicates:
            - Path=/studijski-program-servis/**
        - id: konkurs-servis
          uri: http://konkurs-servis
          predicates:
            - Path=/konkurs-servis/**