server:
  port: 8080

spring:
  application:
    name: korisnik-servis
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true

